permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: depot/setup-action@v1
    - uses: depot/build-push-action@v1
      with:
        project: depot_project_19272af05f3a3468d92cc7ba6046b99ce36f38ac196417e24fbe43812a5b70f2