name: GitHub Actions Depot Demo
run-name: ${{ github.actor }} is testing out Depot with GitHub Actions 🚀
permissions:
  contents: read
  id-token: write
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: depot/setup-action@v1
    - uses: depot/build-push-action@v1
      with:
        project: SarahPersonal